### ISSUE TITLE
Intercept 401 responses

### ISSUE THREAD

**Issue by lukashambsch** [meafmira/bs-axios#15]
Is there a way to intercept 401 responses like with axios?

Here's an example: https://gist.github.com/yajra/5f5551649b20c8f668aec48549ef5c1f

**Comment by meafmira** [comment]
@lukashambsch I think you should use something like this:
```
external promiseErrorToJsObj : Js.Promise.error => Js.t('a) = "%identity";

Js.Promise.(
  Instance.get(inst, "/")
  |> then_(resp => resolve(Belt.Result.Ok(resp)))
  |> catch(error => {
       let error = error |> promiseErrorToJsObj;
       Js.log(error##response##status);
       resolve(Belt.Result.Error(error));
     })
);
```

We need to use `external` conversion function because of special behaviour of standard `Js.Promise` module that returns `Js.Promise.error` type.

I think we should add something error handler for this library. I'll do this soon. Thank you for this issue

**Comment by meafmira** [comment]
I'll also add this example to readme file

**Comment by meafmira** [comment]
@lukashambsch added readme here https://github.com/meafmira/bs-axios#error-handling

**Comment by lukashambsch** [comment]
@meafmira Thanks! I really appreciate the response and love the library!
